test:
    name: dfsdfsdf
   imageResourseDomin: http://192.168.10.79:7777
  imageSavePath: F:\IISWeb\Images\
#    imageResourseDomin: https://www.iamjoker.cn
#    imageSavePath: /tmp/images/
#    dev:
#        url: http://dev.bar.com
#        name: Developer Setup
#    prod:
#        url: http://foo.bar.com
#        name: My Cool App